[package]
name = "imt-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
basalt = "0.20"
imt = { path = "../imt" }
parking_lot = "0.12.1"
